language: ruby
rvm:
- 1.9.3
bundler_args: --without development
script: echo $MOB_SSH_PRIV_KEY && bundle exec rake test;
services:
- mongodb
- redis-server
gemfile:
- Gemfile
notifications:
  recipients:
  - mobilize.server@gmail.com
branches:
  only:
  - master
env:
  global:
  #key file
  - secure: alHzm4UfSEWGZftSuNdLPYtquedLSx/lyRFZaXmnsFNfh0mjlPOM1K4jL8alj8/Tk7t80kI0MEGiXvr8Kw1p05MmT1alA55U3bEU5wl1tifMniRoTr9hHqzOODMwCBehO5DvFGLz3HT/UvA4D0lc2EdGYsTGTrJ2XCn9NoUdWHc=
  - secure: neyHHT0COrMYs/SwhfGSr6vLC0huvTWeetG3VQsYD7hz55tNoEfQkeX4493rJQfmTBciNwxslpBtK+JmpWGt8d/wHOLyqW+SOSV6dBFzujWszh6D5L4O8qOPQgWZKsUJ/YYWoZ7HmYuC9JMEPQAwUIKQKzqIwwicTLMg/Tl+bt8=
  - secure: ThBztC0eQw3kf1mKgW5PV8L9SDdcLal3pIhWpZj676kduDpoPSHAHVrYn76mEBDcCPKmQQ3iM+uKljnBe8bfY1Kbx/8FuWDHLuW8DvP1WCvBC1Biy3ifav1Y+sN3riA6J5Fu5I/QCw/z27gDALwPAVBALTmiCcoIof7ddxzXzns=
  - secure: AZmAu930p9L+Kb0k+VW3zfcx68IQ8BaT5c8AqY5PqSnDi/xZOg5XSupSCDotZABbGS1tlvtub0ddWu2Icn8i987YsN+q7roUZg/mp4B/IknOKMTA0NfjGiTB8Itc5j3gQdufrJGsw47TSLNsyQHleSF+2yQ5w77HMSeMjQZJIcE=
  - secure: nUPB5/JZ4QTRS0hWIaoKiS/emiGP9AJ/s1bG8Nq3292afdOUsRHTqtB6/YQpn1wNuSIHspXZ9VURlB4hyoTOJiMyAFHjpk+2pbNRf4N9aP+c2Vk4WV7Qpz93fNNtoZ52ev9eRMmHqpqF7/sA17hmjT0G3CmKV5OPSaFras4AnP4=
  - secure: FNyvCgWTfy0+89MYSJtONcosMpCE3rwUXqGxhp+L94qWVUO/FWynrBbeUvQi+i3uxbRFVHq/HhTGSKMt84OhX+KEuWfhrIw1ddbKjIkUUrwe7+lfNjhM4jnTnFi/ZJ/SlNm1uSi0BvT7wLmWFzDgnWey0nZ5PXhjtr+I9AXId9o=
  - secure: XZgiYPJ9yWcrXAVVLirNzW5ECuwtf4UIJSKk7B2kTiBBG+s5xCkj7bHLrPJ/UB9BwtnWcBuRvP+lss5BQVDI+3L+RBVul1CjmePjEfykW4xzgg7OtALj1ij8MWRUmK52fEjQHFhd23IYNT53ePmvne9w8ZvV0flejZY7/Pg5jg0=
  - secure: MIN0OqG5wM344H9KLudc3TZVyb9aPOx6vysArcN0QgN0zSBAeE94JbyJfxcBTPFKHz6bBgqqqt4GGrpWdJNNskHvlXAMkXhuzUKX1VMzDfp/hzypO7O7zuJADSPgPYZeMScfeZLQvxBNvjmBUH4x2KWDQVQAfdzSywT2qLoIMEA=
  - secure: RViY035pZBiea1A4aiS1h9w1D4fX7GrKsDVByWMwkf9KgL6eaiygSt7aGu6etrDgUazJgKdTrSTafHk3PAw9ehk7E7Z2K8Y7Oub7IGwMFIi98SLSlwueHHd8wKvPY1yMBGUqJlHNJZiCjS4fB6ggoxgeVcHPekSWgBN/khOXpW0=
  - secure: QjAHgNtiIJRMMO88KAnjMmtjPORXUF5AEXxKfQgDyMLxAzm37VDINzDZEV11ITTCw9Z1PmSktDV4wFh1wjD5yNPC2fD2jboxetI1HUnrjwDGWoBk8unPpqmN31U/CFd6zROeF6EsPLVd+npqv8K9ttAT58MRZxoTXStssAmWP1o=
  - secure: l+ZU6uC5ppszIzTXCJlLblE83t+rQQKc1Px6slhAXmHWS8drDN/rLhq61Idv39qFOWLy38EwdFLTfR9nW+BRg/n8wSs4IQRPxN0B4/eM2+5gnhC4fOow8UYOuzQkIvrucD25B5xEpOxHItSzi/dsL4/XXdrfzhYDaXFb1tOReMU=
  - secure: XpB4zTjczI156uc9i2o+vFZbAld1mPq/GAphR+B3BLMfprEIzGW0zhgMunx7JANmbt23GwpM1VsbQfz2FldpTv1iIYvHC5cDMcKEg7Sxn9GMuc8gUh8s0XhCkJZ/LlbCCuM/Hg/c/1NzomJj4qwwfdFnYgkoEGEzkR1fq66LHSI=
  - secure: T4uZjej/G6qHFnnh6IlEXJZo0f6ErEh14QmCyzFCeKMUKVNckj+5xTUSi2UFM5XxrBpNxWNETgBFFqsZO4BQhXJomplL/70aTK1RrbEa9K/fj5VR3Sqm3nXKgQ2d9DogMwixDzxryst3M0lg0LmwqbBBUlq6ZPhz9LsnTrHlOBA=
  - secure: lAKfpDbJT8rVKr2sy/AdvYrKmWC0A/p5QLwvE/s3aszosB4weVB03m9j0RXYWtYpJ5cdOuPG3e9BMjDWBPujnXYdnob9S+/z+qxIPedLXjH050saw5p9r1Z3wHdOoD5OHhHlAghVJqXIGsYQs+jCaW7F8neALOYHT6y5MGT7MLU=
  - secure: CuBXHVDNKa4F/KAsrYJGMINW5mcw3kTeiwUYQBQip7Rxtp25Psix3Xgf/yph2qDzi8aeFc/IIJuq7wNNRLUZdly8oXdVmm14CnRzE/jGlSL1xMIcwil5J8za2CciXq18pITCHSuMjpW4uuqxlzcChOKv57TLQxdeWIY/PjGEeSk=
  - secure: Tcet75OD/KYeZGxtvuQZMkeDqBzOVsSrdvWmFWJsLW4+JFvci2dxvmMHTrv3RZUjpZu6KthcHa6tSBGy1PODi2i9UrMi2ci8EsFA44jG4NMFi+iLR0SdnwcEbA99Nd0LEjubwLXM8StvbMmH5zbcocgiJxOg+jSpODjOMT06b/A=
  - secure: GKBO/7zmOrWKIS0uSZOYEdt8Ymw/iSSRovB64nzFAr+XOUmTBiUXfDLZuuJE7x0WIlMGrY32mU0NDDeXKR/yaLf6Wff4ZRpKuOyiwnLCoR0BZJhbxtujsgg7yfPjqHe868hmxDPkkPQ/vYolJTJ5NTspYfuOGWqKGQ6b7A0H5VE=
  - secure: TXgMzA6dhu2TwwF85S/2/ypKzad66+DUtSd3l/GqhrFWxFJ4mM0cMtc4lbutqO6Wwfm+QwuDkKIGi1rRk11zO5MxQ7TTlnEClxyZyr0aACkWIT3vabjn7Mqv+1JkFHA2RyTAE00oAKpMaFLKaGutLN0ygiaIiEkFPsD7ANJw7vY=
  - secure: a2CtP8Y5nRfADHPc/e7zSvWXeR9/byOuY8PtxitxUR5wAOxeGIywMAwlrGEOSOQeY7MMMX1ncRVAT02gKI3bm5QKGGwB3G++ayVYMyiaZzkD2yCCeOkeaAxioyzMfHmTsIsw03YnOHU5U/b+VHMgJEKLcYMmmthGjdivw7SHLZo=
  - secure: QnRY1PXD1fwCHyf0tk5nE64uYb56AkYyTPuBF5xGH8OWenjRPbRUKr86vj+XDex8mEW2JvhXzFFHpdBOlNjrUICiEzgQ+rYVkf5lAw/WNAmWYiaEWkBwJmItd1h1atxTxygp9aatrOpKcQJjPU+AxywlsmTcIjz3MjfOINJ7lfI=
  - secure: QS46cSqTgVDTzzRz69EHVwIKhj8BbAYbkZGwal03aF9RFTQgbLf4fMWI94FV3MGv2CM/z7+J961mC7IJ3kG7XmBRr+r0BcGAOxBGZUPA/qPmIWEcq4Q/qimD6w2NILURwibN7vBOAuCHhvPAQayPffia/td17z6/O45kpF+zC+g=
  - secure: BUbHKyS9YF9MrMuCDFyuCTtjcStwSp6PmNQaVftvVea1TBcadUOW/u9H1f7GyL79qa8h9J+1fv/522hqBwk4QlXlV1KWZtowap4icUfYNqQ+qs4NWqXegth88g1jDTnB2A/pe0JObB+ITcsDuXI9NtqICNV4+DGdFw4uJp3LDXk=
  - secure: A8+sUSGlga93Zr/ckhx4VCOCx8kfjTY6QvfzdouqAQ/hhaoS+A1zpiLp+u8TnVUOnoM5XsTKuRHbD8jPCS68EssUhtQVpA3+EZVyg69v7RA6uB4ixqtBa8EphMLjp0S12y5moNqrhplR7eb7o12zaAaR7evMJcJr8VdxQKOjkM0=
  - secure: KtM9fJFkOHU9H549f8/fRFFA+2SApdebCUSvgfSs8NJDifH2qFMdMb9Vg+7lC4Y2wo54ca60vyQ3MzzfXJNL85ziZF+wj1HQEzSWs/sZoil01SA7tZ3WIysFMQ3fXMS7o2yzXjvn/Ri9RyOnYrFSwLAQTfOv6zzyBgf7ICh/AkE=
  - secure: bFAJU/o18Q3LUWoByN9dQ3Kr4qbONcvUUKFlFciMZ75AWvQPIWlY9aIuIPjv1ThSQiCh2zmAzblA3o+46q4X5O5PsV95K02hvPOG5uVJ1nzlXN4EHJEAx4e4DKFj45Ibm871nX+MCCvCzO2z1+eVPC2hZ4uqXxmPRvPBI7QHQIA=
  - secure: dFjQ0NiMYVMIXicqUILGm2vECUkBw4UvT0Xa/F7THXVJ39IfkR3nZmadJvpu2spFvassoxzmAeLgrmz7NyNMqqXi2TQX4WT6czOn6dxrU+i1wv273Ej8o56gi9x5GZuVxrpvANF1Zmej3yJCHLbPZQ8bq2rEISe7ihDlFrzQJCc=
  - secure: cTvrPlhYNJC21C/h3UaGmWEJvz1GJMyZCH7K78oRcWBBz1RQm42kZuIaOCZH0dQ4EdLoZboxw9UY+trYYnypd7C4kZey22tCIWkqf82uvCP4Fn6Sj3m1YYvEPotXNubbadi1F1u1ICkRw3Lp4kMvzWVtQSqN/Gtrlnv9IJESSFw=
  - secure: a3CrqCBGL3jSr7DdKixx+ZM25gsAIGEsNkrzQ1962ArqLxFDKKf9fcG/XVL5PdUkT+Yweeggbwt2tKKnzdAP/qG1c48OiUSQr6Hx2dftrciQpomHW023/rtyKSo1cX+xTWisrmN/lTzLYbHEVEroTDxQzdTbH/99m3Jv+/IIB44=
  - nl='\n'
  - MOB_SSH_PRIV_KEY="${K01}${nl}${K02}${nl}${K03}${nl}${K04}${nl}${K05}${nl}${K06}${nl}${K07}${nl}${K08}${nl}${K09}${nl}${K10}${nl}${K11}${nl}${K12}${nl}${K13}${nl}${K14}${nl}${K15}${nl}${K16}${nl}${K17}${nl}${K18}${nl}${K19}${nl}${K20}${nl}${K21}${nl}${K22}${nl}${K23}${nl}${K24}${nl}${K25}${nl}${K26}${nl}${K27}${nl}${K28}"
