language: ruby
rvm:
- 1.9.3
bundler_args: --without development
script: bundle exec rake test
services:
- mongodb
- redis-server
gemfile:
- Gemfile
notifications:
  recipients:
  - mobilize.server@gmail.com
branches:
  only:
  - master
