#https://gist.github.com/lukewpatterson/4242707
language: ruby
rvm:
- 1.9.3
script: (ruby -e 'require "./config/deploy/travis"; Mobilize::Travis.base64_decode("mob_ssh",23,"test.ssh")') &&
  chmod 0400 test.ssh && ssh -i test.ssh -o 'UserKnownHostsFile=/dev/null' -o 'StrictHostKeyChecking=no' "ubuntu@$MOB_AWS_MASTER_DNS" hostname
notifications:
  recipients:
  - mobilize.server@gmail.com
branches:
  only:
  - master
env:
  global:
  - MOB_AWS_MASTER_DNS=ec2-54-215-215-64.us-west-1.compute.amazonaws.com
#mob_ssh00
  - secure: "OsTKT4Rc3Z2AkBP0//F4gGoapSfXOAWxebADt3bKcZTYuclceP12BDaeMaKBZUkY882GZ5XO9D4LZFOECLeuDo1HAzCmZM5xprrKcH6XLWnVRJBZ6/vCDKnGO6QJ3tsMozmO+Mm3SixExI73+SZxFEkgktm/QnDm+T5KrWXKF7M="
#mob_ssh01
  - secure: "mIsdo0LNFLdm+X8xNo9blLhQy2MK77/qK7/qLIQWzyrONaDYd+HE1B1cQ2BXg4g5C/M9VDY3cGz0jIUqJHiIrzthAzQvZGZbBdnMeX9xRppTc4BjsUtmOI825RzzcMljJECdgfwgkDI+rOLelZnEZ3pj7ZtwHAiJd9J7HQiOLM4="
#mob_ssh02
  - secure: "kn+A6Y6QZKLpFr0jGcfLOp7zB8lMa0FD4GY8mQrz32va1h2T+wVrqhJd85K5Qm1+Ii2F5CjGZB3W9Gb/GXzc3igj3g0Ho4P4FjQz8aDDDMaxpNRDIVmfAkR5hO4eVloCeY2AvYtTTH+D017PZo6sTXfgUTPm0ZpgEZ84B3SxMbk="
#mob_ssh03
  - secure: "U7Oy5cg/bddQujsq38oa73NSP7dswAx3BIWX6HheoRwI83h464TLTWHe+PVxh22b5jJdfBfCfm+fTXuzSh1ZIqTH9JcPVW8bswjgWkGBdiDdF5QmZNcSrTtj84/weKU7a3Km1XOq+Q7l/qNm3SiP0MeUQBYoauLXgfhYUoEeC7c="
#mob_ssh04
  - secure: "EvpZ1RjKA9XYJEyuRBg/q6srXN2qYraI1w8i98Od97YJmJPqbvFo61s5A7ImiNnoI2XNYb9c3/db5ma1v2SDRymzAaCHePEVIoU8Oj3aIJb4UiX9/aFPq6/jv7u1gJ0cAzCg9wU34LTS9t24OY6OUxzaYn/I/A91KWengL9/dz8="
#mob_ssh05
  - secure: "dF1p/VAxqvRK7kNiJGxPB/x3xuxtHHwJRxQoinQe0dhCjZ6dOXPsVBCIUO+W1jBIjJUanIavAptgERPacJRZQemoYTdeQSyGdPTtnv6ubQxzI0mYVKexkjneqHT/394M6O7+pOHSMD774DXGWTIGIkWFieYFQbJ0ain2p+rF2pk="
#mob_ssh06
  - secure: "K7PJy4ju8kBO+bUmRYPMl0k27L3CeOp4pzXGc+7x66Tm9VjDDfppn95FRuPoQcrkjSS2XQT9yqd77Lh6ZthMopDOxJGSWs++kodnD/NYwvW75Vazyuz0u2Jv2iSRbnTWXbGDqKsUF7xSy9HwQR4+qaqoPGvMqvofyAAsdKYv8xk="
#mob_ssh07
  - secure: "Yi1kb+kaE95vWQGN6BeWyvS4xVCnwvsef5DT3lXSNTFq5LKiR/yjZXlS+uT0YUX72k0m6mWXSP/+zWQmRnM+ghsX3Aa33fPBjPqO30Sg3KynQXGdEIpcGcj9ClVVboGkLsJO7krCyPWNrLhoCgIcu5aRj1XVxxHe6uC/VCDEZHs="
#mob_ssh08
  - secure: "jTE5HBY7K/iQyJ5zRnrm++pEKva47gpaHAvWIhwbhnUjIktVdhS1cvSi4i8d9ef4FFysf7IEdDwtDskNMkFHs8X+2i18XcJ2v7z3Ka96+hleci4u7116v/4IfqSW41ni16izM65yvJxT4zVPgjTq5N940G7sZIIANu0E2AqX3Xs="
#mob_ssh09
  - secure: "eH7fTdIQqqgTDeIqqdXHUxB9lKpdWWRO/jQTT8U5OTBkKK6Mk2u2jIf5i+N1NMRi305dMZfEYwHNucJPLPWOJPFeO5ybMeCPUhdouSojgRumsjWsSPo5PyF2MHRpeamzLFQSEDBMsF8UNYFp1ZAaeBcPqV5JchYtuCA78Y8iVRk="
#mob_ssh10
  - secure: "dfmPjlrAycIqZwjw4uXxnptp6gkqgrNuYITVvzZXE5smzJFBF787mc4odio4gV6pY/X7lCdcktLgu5E+D4gRDxmhyMrLBMSsRG1G4ow2dBSQRTD7wP62EU3dmCfODfquYWXeT7sMqhyLuTwvmM6paOqUSd2ikCuSl2NhBf3dhHs="
#mob_ssh11
  - secure: "QDgdyaEKJ+06dB2umFzp+qfW87Q65bQJkExcJ5wv9CBD9ZmmZor6UgEgNE9uA8nuI9nmhVpITyhoQRNXXIIstTEO7jl8TV48WL0LABfKnVjXpBl0uu5mteHGc9GBs9v7F/Y1CSJaPDAIj1b14ptWtqRQ+pPNrQSo3lhlF4DUxOk="
#mob_ssh12
  - secure: "FcpEfkECRGvOK52Yt6VyrtDYuw/910f1oAA9nh/Nu/6hxDO8sTxdhbGkEKUpri9mle6VBVPpnLHxVApVKN2EF8L+CgrKmAoRVF2qthuFBRNrpTQ1ctPdfumADLA7PD5smd6SLHSd/dtAs2EU7cFZL9E+nb2jQ9cIR7HVTf7cW1I="
#mob_ssh13
  - secure: "gahwAUGAmrBLc57Zj4qOAgJ2h4QR07hWvSuSjNxkGrBfM2xdb29VzDzigtulE3mUE74C4vefhzUerXYtiLnPXwQyeDrOHafoQCW0b/PSUDregGaUnga8ZcYpUTtthBOaE0AFGbzLHCTAkaGc5ZmJOcLPXEMGndzqmRhCqzUUPxU="
#mob_ssh14
  - secure: "Sa+FERlaJd1K6fVEfirpO+KCzXg6fTb3A05BlcNV8CIsiT2HvT9HrHrge0kJ8nGry8nmZ0VX4o1ZgVT1Uv7EGCiDelmCLWqBOtfiygyaRLwxR152V+bG4L+78Z0g1wPoLfHl7+WSvsvAzI9l6UtRsW8uG3JSdIt5MWxeC1nfn9g="
#mob_ssh15
  - secure: "jGzas1BJ0pGTJyWBr+Cu/cO/4WVGQT5eKCXdyCZ1LFO64hsiryE6wztSubR7rLQBTLHaJo2xEuvPz50aoyqDKXIU8uZ2HPeaxxYnLR8tYdt2IB1jaZkInyFcV49lONbIvOyYBvAkWA/xPh1ibilxl5yQzx+W++mh/WWcBUSg1nc="
#mob_ssh16
  - secure: "hTkkGlqTcVh9hHMDMsprxQZoCN5AA47r/C+YNKoUFzQQvZi4fqjCvnuUYoNRJYbQT2Qufne31YO0qHCuHyGmFSyDiIWojxJGpxOsTOmtYODZPh/LKvnsOXg/+gAXP58pYjwguKjk549LQdUuq/gC4L0fbGPKhSEtuy7FWlgWvNM="
#mob_ssh17
  - secure: "jMDCKPuCkTwpks3TZ0FaIrj5jK68sIzqNItF6HpDzNGV8ygifaoFqDXt/Vwm1WMv2Lb0fr2GnRd379j9X2UrKPKKTrcnoaCVN1G2GiwKeuy8mvZiFJO7SnCXCnB6G7rmCRvJnrIFR2u0WL6LWWeYAtsWVFMWQwBckmZC4xNsTsg="
#mob_ssh18
  - secure: "FgqBn0IJs+e+0VW6fBtoZa5EdALcWhtpccWVzeuo1u/RHBOeszaKnmQbw4pYRkhGvp4mXqAcrM6gt0UVPW++7+VeiVfUT3dNV0lfJkRM1+A8/0Vx0ZOpd/5Vblu5Q4bbkscPQycwU9uLraLoG2FmhqNolK/31ZynBNhZ7C1kRhI="
#mob_ssh19
  - secure: "D5OtRpjhflCCJ7RikcpHqilxfTUR7pml4QgGg9C0j3iJEn92NYGBeFrj3sLTI4h1l9mx+qD6oqbVgB5wWEr8p2AvQPAd43yKOeDTaw8Bew68+hQV/HCFcnS21dmqfPvSlOrcX6Wuq+aAEUG7T2jVGbYk9PuVk2jOqJuLvyyFvSY="
#mob_ssh20
  - secure: "Lig1kbo2j0HNu4GG0/Hv4CU2Pc6B/XMscD3Z001vumvVOzO3ZwKJ1TlQGBew8+bDV44NT4snwof+HZSId+HI4KCQcP8FDnoc+UEE/FZgnk7teKGJ5N4E0GuIKRuomd8j3cTuW8CCTm2AuYW8I6lR63Taouw2RV60dscpdDd/YFI="
#mob_ssh21
  - secure: "lser4YH3hmf6fwJq91u5p7SyffqkpWjq2WAP4I2XGVELP7AYxolnqU4GfHm5u9g8CGiDBtxa/edmcl0B2zNfbNpQU8lA4a6Et8jBScYHljXMpc5Ggyyte4Qm9FKt0F3WQIwB99VzQo6bc78jCPl7LxGFiH2gT6G8E7uuM8x5G5Q="
#mob_ssh22
  - secure: "FcgT1BPaPo6ioGIhbCwV/3ZA41uz/dUYBterlKWxc3DN6RS+KOrPP/vuGzsfh2pv1zlbha4eoGcEnOaszhsoDyB7Pw46xyyTNL27kMgHWD73upXnG1aSP3r7Q/IszBqOk3il7CqNsHYurbOPqvulYtOji9NId056GsBBf4n9M68="
#mob_ssh23
  - secure: "jl5vyi6tHO8na9wKtEAqUkXqJRXOcgNEYMIoE6/1dh5LJI+HyejvoI1mExy/IPiP92NoNR+gqSTP6NXnwwgyCpShZgzWo2nNUKOItU9X4g8t0K/H4cWS0/lADe1/766zLg/UL3EL+P2HotLGyjc+KhLPaZ1rtbGznJbhH1msLvw="
