#https://gist.github.com/lukewpatterson/4242707
language: ruby
rvm:
- 1.9.3
script: ruby -e 'require "./config/deploy/travis"; Mobilize::Travis.base64_decode("mob_ssh",22)'
notifications:
  recipients:
  - mobilize.server@gmail.com
branches:
  only:
  - master
env:
  global:
  - MOB_AWS_MASTER_DNS=ec2-54-215-215-64.us-west-1.compute.amazonaws.com
#mob_ssh00
  - secure: "FXugvQYkJjxBAucu4yX8X7EfL9lAj+e7z0oPGGgV2VzcTcKyf+3nHWXggCa7KtZMl5OQSZ0j9MxdIMpcToPV2G2+BgbgXQB0GBnQulP0wcPsko1RkaxYGBB/+FPEiSu5Lm0m0O4Ypc9XnUInn8p0XXGF1TDklD7xKoHOHOhzegM="
#mob_ssh01
  - secure: "EO4UIhpASwF+weLtUty5vWvbE1UwqOCfgGyzWIOr7ACpUAQcdx9J9euiU3dULpy/5qH+8vIV2WAEVmoyaBLxNHQ/0hG2XahbHo2nyz3KuLWFORAPiP1XAEWviLbLmrugdxO8mGhQieLPeRZZukeNWgvt5PBC+m7JuvcKVTyEfR8="
#mob_ssh02
  - secure: "SReURPerAvj5f57HpKB6UuMXoDkzumIdd5lhDEHD8/mR9XB/E4uhz6oBKFqTK0MrEBMsD3q8dniMvbz0K+NjruF/BYgBk5CA1HRR8gwWWWUUIYCHHBAD07jMugTUz+fCUvO0lbFcGp1MboUUYLsvrqvq2yQpinM0UU06SxgTmmk="
#mob_ssh03
  - secure: "Fr7Et358S6dLbYrOo2LPTGhpXlPmqNDjxJmpmCI9Hs8tzySSALvQzfio9IdlHEv24GLnJariPQNplgFgjpXXZYcx/H9v/jnjjozdzhrDWWYMSW6voc48B/7/r/bnsIR5lo5pxLvDTEfoLg6XOBwGUwxaSm/2C8+JZClxisBZ9RU="
#mob_ssh04
  - secure: "OT8OJjJ7Q5Pe1VnQ0hNaoHZRJAocYIZgC1LxLRr4n8Ov49klgWdcX8FZ/n8By9i25V1ymUn4NV+g9Wb3sJEUfvKugPI10Is9rM0OgD3uT6sugCcKzIKikx/3HVAy/f5RlbPoMwOotRL2NXigULJZaqcDhonUtTu2E53kjiEYC3Y="
#mob_ssh05
  - secure: "DFNaZ270M+wiNK45aGxKmL/Us+rE86A+UARrBg4PaA0INQIN6gUpjZ93HugNkhqWpm5r37QlLX0n2nhX1okZGV14rJwqBSSzdnNNmw2jmwSkQkiZ1vMwPs+Eos/bsoC+5VMrEhIAZIXNfisXIt4R8bT9uMEO2SPOJ8VA7us2dAw="
#mob_ssh06
  - secure: "heFRKptlDF8EbWwCR5WNlFmgnPesJ0ZYsZz2E5SxObdMvQhr/l3s0UnHNS5dxAsiYhy7kExmABmJtJXzfgvpO2F7OamRZKKv3CPJIc+0QNitwdX/QxvjtPkyI09onY8lLKJVfq3mvpi7LPepv2666SWLFtZn0k5EoI+VS5VOrjg="
#mob_ssh07
  - secure: "P4l9kcA2QP9ilWdj8FpdTv/M6GwHYiG8kTDHzNDU3l+TfjHd6xBEkxNDACzRlIXf0SBi2R7HgRuM6Vo7fbYzXo9IOL83YG1FPSBWTA8kr5ANqGkWofFilrTXlB6ad/C5XOGKao79KErOWh20SlixKo0087YMtmz6vGDfORzi4hY="
#mob_ssh08
  - secure: "Y1HFvEASWrO87CtU1MpDYAFGKFJQb96KRpXqVuNomdj7KIwWazhsJBLTzDbRxEbsf88HSZUcfaw/3zVelecZ24o3hRtqaeSHlf9PslBpgeO4lf2AqT8Wqa+Ymuf0IP6w6vwPDQTBa5GmBojFH0aonb0BdnCZ2VlEkY55qY0H0fk="
#mob_ssh09
  - secure: "HbnNM+ER/2TPzGrrGuUYH9J/Dp+tlWdmOy1nEi9D908SZ0QamIARR6QlaNQegRgYHOSbotrBSnBgYs0KeNEV9c5kR8uaeikpMHKPmTXF79buGTSUH5Wvf1ulf+XVEX1gCfaz+SEOxsY/9kT8OBQRiPeiYxfVtrWOomWuEf+XjBQ="
#mob_ssh10
  - secure: "Z5ScDv7YuHQNOvllzL3/gy3otkN2xPLCR9zY/nQnyqpNef2BT7/Ehnw6PYGzJtxSTL6CtxZzA7ixqfgERp8REW+XuJUdvJTT+CCoYHyzy/R4WOrHNvfx1ZE2Qfl9UH4h7zrWFS+V7w4iSAl5XHI19mNLo7Jb80XHcHuY1QQHL38="
#mob_ssh11
  - secure: "cG4AlXacIynlGhEJlmA70tRMohyuE3y8vUkWrLoV4HOntyc48KcxBGSKV3sAiTcwHobSrN8D8mSkxC/oRKXIcru90dpZEWz9RuvqpZzlEEMoiLd51tCG09lYiwU48mnB/38ti9ttHBDQDYGM6vSTdFA248VRffpLRk4gEmrZx+I="
#mob_ssh12
  - secure: "n/f2IP7qXypo2HxWe4gyGtiWjJVsx96YMV8JDHeB9S8aul6LOWQjfYf8PXMLkSXflCLvSq+NmGub7n3bHQj9L98uvgQs7Zx577UpdsbvHgQ0LDunIspyMt+kZnxEXDpCTYEvLkA6RRJShks2vntiCTfOww9UwHIXM6AFsP+gAwM="
#mob_ssh13
  - secure: "FXy9FvlSVfsDco20q1IFPEjZ60ssv1I5MIwb+O9dyh+E34dB+Ro4TX1KWYlo/7HxbG/XxVAgU0tru4/IsFnQD8JjR+HVwBTm2jBihsxC8A2pccnN+w6AGpc3YYWbCx3FxkqPfl2Pni+Mi5b/A0axfSMHXQb9dFr9xS74AeIJgp8="
#mob_ssh14
  - secure: "T+sZ5XNITCCTtQi1b0wjU9bhknisnr1CwxrbRWg+fzlmjKHy3nfWfVMtHaZy18Bui61E/NOKH9YrsqBtG9PgHTpzFsHAAxLUnhk0hajNCD79jCZF8jJGHqQ2b7E52NNBr8vcasIZc2698Z7FpQebaQ/LlempsS4tjznfsxJmlgE="
#mob_ssh15
  - secure: "gT8M0HJwIZf98SaJwbfgJuJ7FSsz4qVIePt2BTTzNKeBuXQv/H/lxrwLa0sdbOsKQ8QXB4gQfd4tNa9ynRUj/Dnms2TLSu9GCLjLRA81HFeSzynR2jPi8oJjcL0Domr5XoxnbnJyXsz2pVWzcxhMA7OAFJejfpQYlWAw1KODaYc="
#mob_ssh16
  - secure: "kE/5mRt4Own4nMCXFNwIb2edawmwmpNZxMJBs2Wy1bI3r+iyh8Y6DD64rwWBO9nY27S3FoEAAc/FPivaijzwWm4AMTnM18ICnqNF+JaKkNv/CODcileWBm9ufcIL4C7uLU6CLYRexxsjDdMbdaRtOQ61x3wfGrnicxT0EHFWllw="
#mob_ssh17
  - secure: "LACMki+yP0AehkOrzz0CZGTSPV/HBj57sDFueCg0fQeQJY8XMazcd3J/+1J+8OU5cEwj56e3xKeUpS16f4KNk9bdxZE5XlbyN8eFGtYqyUvFBISVG0vQrvQd5W6qvjaAa1w/0xq2kEqrVeg6V6F1DirUvJ+4qkOC23hY5HrUHm0="
#mob_ssh18
  - secure: "Z1I/gRFvVjPqUzv/gZIHESHjFXfHtvEpS9geAPQOtWhbwBr1cG8eU3w/89z3TL1z5fkUMjzHJeF6/i21RCaFMOxVEXnmfZsDP8sgC92W2Z8QNfVrl1wUGIttbAQoWOgyu5O7E7meSsXnn4unA4hFcvCDGxE18KlsCak5l2N7LIU="
#mob_ssh19
  - secure: "WQKxORpmU746zsaXFzulVsOHa8Lg6GWmyQFcCf05cG2dIYYeeDfmJcJu/A4QK10WKJSZZzQJeW6TifLIYauaX8Y9PJ2s2hjVOK5BF8fndHxlWrqIgPp/3MmUvC1BJNeWzGPUCwESJw7SO56PGYMvvQ+ibzzmH9OMWjw4ZjjITRI="
#mob_ssh20
  - secure: "F3QMgG8aBHf4YUjEt9lWkxCNL26hTQ9cAUXO11jkaEbc2b+ZPicI0lTKxCs5kBJNmPUR5A1kF3B1Cj2EBADs0RV0bvVj0efHDe2sxv7CAonQktgBIYg+I3nAtG4Yv88BcYIrs4enIMcyB49L1uDjaHC+4g2yzqZFxNa7Nz6TbEw="
#mob_ssh21
  - secure: "NfOMmK3t+gCRQyyKob5CGiohfyIIiNkMNZJ5p5t7Nnr5xpOWw4j36eTJpeUd/7F7jQJ58NhYkgdRmk8oT6Buv/aW2Ur6OIB4jYcCPaOM+XZL9wY0mMCVN0KDqoeOD2u/zrtAN1DU2EDV3oZbAH0Qdfs14cs/XRxR5+kjFCXbBmw="
#mob_ssh22
  - secure: "O/UTaN921/8m9Rk+YjKllmdZ7JMvSvVAWhu+KhM11gPmiD7R5xazDbS1C6tvgU8aKt6nQE4M0DYvBSdiWXOvBIwTFAEPrwaM31eXS9PJ9kgAnZ7yIb85/Jz0Rf9gznhYz1svxxYQHzWOObKpEbi6zojoIRB5ZIzaaZhPncgIDbM="
