#sample config yml for mobilize
#test includes special variables for running
#tests, found under `fixture`
test:
  redis:
    host:     <%= ENV['MOB_REDIS_HOST'] %>
    port:     <%= ENV['MOB_REDIS_PORT'] %>
    password: <%= ENV['MOB_REDIS_PASSWORD'] %>
  mongodb:
    username: <%= ENV['MOB_MONGODB_USERNAME'] %>
    password: <%= ENV['MOB_MONGODB_PASSWORD'] %>
    database: <%= ENV['MOB_MONGODB_DATABASE'] %>
    hosts:    <%= ENV['MOB_MONGODB_HOSTS'] %>
  cluster:
    engines:
      count: 5
      workers:
        count: 5
    master:
      resque_web:
        username: <%= ENV['MOB_RESQUE_USERNAME'] %>
        password: <%= ENV['MOB_RESQUE_PASSWORD'] %>
    box:
      user_name:        'ubuntu'
      private_key_path: <%=ENV['MOB_BOX_PRIVATE_KEY_PATH']%>
      keypair_name:     mobilize
      region:           'us-west-1'
      ami:              'ami-fe002cbb'
      size:             't1.micro'
      security_groups:
      - 'default'
  work:
    timeout: 600 #how long a job can take before it fails
    retry_delay: 300 #number of seconds to wait between job failures before retry
    max_retries: 5
  log:
    level: info
    ljust:   75 #amount to pad the log source from the log message
  attempter:
    max_attempts: 5
    sleep_time: 2
  task:
    max_log_frequency: 10 #how often to repeat log messages regarding unchanged task state
  aws:
    access_key_id:     <%=ENV['MOB_AWS_ACCESS_KEY_ID']%>
    secret_access_key: <%=ENV['MOB_AWS_SECRET_ACCESS_KEY']%>
  google:
    api:
      total_retries: 5
      sleep_time: 1
      timeout: 600
    owner:
      email:    <%=ENV['MOB_GOOGLE_OWNER_EMAIL']%>
      password: <%=ENV['MOB_GOOGLE_OWNER_PASSWORD']%>
  github:
    owner_ssh_key_path: <%=ENV['MOB_GITHUB_OWNER_SSH_KEY_PATH']%>
    owner_login:        <%=ENV['MOB_GITHUB_OWNER_LOGIN']%>
    owner_password:     <%=ENV['MOB_GITHUB_OWNER_PASSWORD']%>
  fixture:
    gfile:
      name:  mobilize_gfile_test
    crontab:
      name:     test
      gbook_id: 0AhErDVK4q00ydE1DRnFma2tJbzM0RGFsRTZKaVpkbXc
    box:
      name:             <%=ENV['MOB_FIXTURE_BOX_NAME']%>
      user_name:        <%=ENV['MOB_FIXTURE_BOX_USER_NAME']%>
    github:
      public:
        domain:         github.com
        owner_name:     mobilize
        repo_name:      mobilize
      private:
        domain:         <%=ENV['MOB_FIXTURE_GITHUB_PRIVATE_DOMAIN']%>
        owner_name:     <%=ENV['MOB_FIXTURE_GITHUB_PRIVATE_OWNER']%>
        repo_name:      <%=ENV['MOB_FIXTURE_GITHUB_PRIVATE_REPO']%>
